name: Java maven environment setup

description: "empty"

inputs:
  java-version:
    required: false
    description: "empty"
    default: '17'
  distribution:
    required: false
    description: "empty"
    default: 'adopt'


runs:
  using: "composite"
  steps:
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}
        cache: 'maven'

    - name: Update maven settings.xml
      shell: bash
      run: cp -fr ${GITHUB_ACTION_PATH}/settings.xml  /home/runner/.m2/settings.xml