name: Artifact version generation

description: "empty"

inputs:
  sdk_version:
    required: false
    description: "bettor-league-sdk version"
    default: "1.0"

outputs:
  version:
    description: "Artifact version"
    value: ${{ steps.generate-version.outputs.version }}
  sha:
    description: "SHA"
    value: ${{ steps.generate-version.outputs.sha }}
  time_stamp:
    description: "Time stamp"
    value: ${{ steps.generate-version.outputs.time_stamp }}

runs:
  using: "composite"
  steps:
    - name: Generate version parameters
      shell: bash
      run: |
        echo "SDK_VERSION=${{ inputs.sdk_version }}" >> $GITHUB_ENV
        echo "TIME_STAMP=$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV
        echo "SHA=$(echo ${{ github.sha }} | cut -c 1-7)" >> $GITHUB_ENV

    - name: Generate version
      id: generate-version
      shell: bash
      run: |
        echo "VERSION=${{ env.SDK_VERSION }}-${{ env.TIME_STAMP }}-SHA${{ env.SHA }}-${GITHUB_REF##*/}" >> "$GITHUB_ENV"
        echo "version=${{ env.SDK_VERSION }}-${{ env.TIME_STAMP }}-SHA${{ env.SHA }}-${GITHUB_REF##*/}" >> "$GITHUB_OUTPUT"
        echo "sha=${{ env.SHA }}" >> "$GITHUB_OUTPUT"
        echo "time_stamp=${{ env.TIME_STAMP }}" >> "$GITHUB_OUTPUT"
