name: Artifact version generation workflow

inputs:
  sdk_version:
    required: false
    type: string
    default: "1.0"
outputs:
  version:
    description: "Artifact version"
    value: ${{ steps.generate-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Generate version parameters
      shell: bash
      run: |
        echo "SDK_VERSION=${{ inputs.sdk_version }}" >> $GITHUB_ENV
        echo "TIME_STAMP=$(date -d '+2 hours' + '%Y%m%d-%H%M%S')" >> $GITHUB_ENV
        echo "SHA=$(echo ${{ github.sha }} | cut -c 1-7)" >> $GITHUB_ENV

    - name: Generate version
      id: generate-version
      shell: bash
      run: |
        echo "VERSION=${{ env.SDK_VERSION }}-${{ env.TIME_STAMP }}-SHA${{ env.SHA }}" >> "$GITHUB_ENV"
        echo "version=${{ env.SDK_VERSION }}-${{ env.TIME_STAMP }}-SHA${{ env.SHA }}" >> "$GITHUB_OUTPUT"
