name: Docker image generation

description: "empty"

inputs:
  artefact_name:
    required: false
    description: "artefact name reference"
  artefact_version:
    required: false
    description: "artefact version reference"
  docker_hub_username:
    required: true
    description: "docker hub username"
  docker_hub_token:
    required: true
    description: "docker hub token"

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artefact_name }}-${{ inputs.artefact_version }}
        path: ${GITHUB_ACTION_PATH}

    - name: Display structure of downloaded files
      working-directory: ${GITHUB_ACTION_PATH}
      shell: bash
      run: ls -R

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_hub_username }}
        password: ${{ inputs.docker_hub_token }}

    - name: Setup maven
      working-directory: ${GITHUB_ACTION_PATH}
      shell: bash
      run: |
        docker build -t bettorleague/${{ inputs.artefact_name }}:${{ inputs.artefact_version }} . --build-arg ARTIFACT_NAME=${{ inputs.artefact_name }}-${{ inputs.artefact_version }}.jar
        docker push bettorleague/${{ inputs.artefact_name }}:${{ inputs.artefact_version }}