name: Common java maven continuous integration workflow

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true
    inputs:
      java-version:
        required: false
        type: string
        default: '17'
      distribution:
        required: false
        type: string
        default: 'adopt'
      maven_command:
        required: false
        type: string
        default: 'install'
      maven_profiles:
        required: false
        type: string
        default: 'default'
      maven_pom_path:
        required: false
        type: string
        default: 'pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${ inputs.java-version }}
          distribution: ${ inputs.distribution }}
          cache: 'maven'
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn ${{ inputs.maven_command }} -f ${{ inputs.maven_pom_path }} -s .github/workflows/settings.xml -P ${{ inputs.maven_profiles }}