name: Common java maven continuous integration workflow

on:
  workflow_call:
    secrets:
      github-token:
        required: true
    inputs:
      java-version:
        required: false
        type: string
        default: '17'
      distribution:
        required: false
        type: string
        default: 'adopt'
      maven_command:
        required: false
        type: string
        default: 'install'
      maven_profiles:
        required: false
        type: string
        default: 'default'
      maven_pom_path:
        required: false
        type: string
        default: 'pom.xml'

jobs:
  java-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}
          server-id: 'github'
          server-username: 'cnadjim'
          server-password: ${{ secrets.github-token }}
          cache: 'maven'
      - name: Build
        run: mvn ${{ inputs.maven_command }} -f ${{ inputs.maven_pom_path }} -P ${{ inputs.maven_profiles }}