name: Common java maven microservice continuous integration workflow

on:
  workflow_call:
    inputs:
      java-version:
        required: false
        type: string
        default: '17'
      distribution:
        required: false
        type: string
        default: 'adopt'
      maven_build_core:
        required: false
        type: boolean
        default: false
      maven_pom_location:
        required: false
        type: string
        default: "."
      maven_command:
        required: false
        type: string
        default: 'install'
      upload_artifact:
        required: false
        type: boolean
        default: false
jobs:

  generate-artifact-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.generate-version.outputs.version }}
      sha: ${{ steps.generate-version.outputs.sha }}
      time_stamp: ${{ steps.generate-version.outputs.time_stamp }}
    steps:
      - name: Checkout reusable-workflow repository
        uses: actions/checkout@v3
        with:
          repository: 'bettor-league/reusable-workflow'

      - name: Call generate-artifact-version action
        uses: ./.github/actions/generate-artifact-version
        id: generate-version

      - name: print generated version
        shell: bash
        run: echo "${{ steps.generate-version.outputs.version }}"

  build-artifact:
    needs: generate-artifact-version
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: Checkout reusable-workflow repository
        uses: actions/checkout@v3
        with:
          repository: 'bettor-league/reusable-workflow'

      - name: Call setup-java-maven action
        uses: ./.github/actions/setup-java-maven
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}

      - name: Checkout project
        uses: actions/checkout@v3

      - name: Maven build core
        if: ${{ inputs.maven_build_core }}
        shell: bash
        run: mvn clean install

      - name: Maven command execution
        shell: bash
        run: |
          mvn versions:set -D newVersion=${{ needs.generate-artifact-version.outputs.version }}
          mvn versions:set-property -D property=sdk.version -D newVersion=${{ needs.generate-artifact-version.outputs.version }}
          mvn ${{ inputs.maven_command }} -f ${{ inputs.maven_pom_path }}

      - name: Copy jar file
        if: ${{ inputs.upload_artifact }}
        shell: bash
        run: mv ${{ inputs.maven_pom_path }}/target/*.jar artifact.jar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: ${{ inputs.upload_artifact }}
        with:
          name: artifact
          path: artifact.jar