name: Common java maven continuous integration workflow

on:
  workflow_call:
    secrets:
      maven-settings:
        required: true
    inputs:
      java-version:
        required: false
        type: string
        default: '17'
      distribution:
        required: false
        type: string
        default: 'adopt'
      maven_command:
        required: false
        type: string
        default: 'install'
      maven_profiles:
        required: false
        type: string
        default: 'default'
      maven_pom_path:
        required: false
        type: string
        default: '.'
      upload_artifact:
        required: false
        type: boolean
        default: false
      docker_deploy:
        required: false
        type: boolean
        default: false

jobs:

  build-artifact:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}
          cache: 'maven'

      - name: Update maven settings.xml
        run: base64 -d <<< ${{ secrets.maven-settings }} > /home/runner/.m2/settings.xml

      - name: Build artifact
        id: build-maven
        shell: bash
        run: |
          mvn ${{ inputs.maven_command }} -f ${{ inputs.maven_pom_path }} -P ${{ inputs.maven_profiles }} 
          cd ${{ inputs.maven_pom_path }}/target
          cp *.jar artifact.jar

      - name: Upload artifact
        if: ${{ inputs.upload_artifact}}
        uses: actions/upload-artifact@v3
        with:
          name: artifact.jar
          path: ${{ inputs.maven_pom_path }}/target/artifact.jar


  docker-deploy:
    if: ${{ inputs.docker_deploy}} && ${{ inputs.upload_artifact}}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact.jar
          path: ${{ inputs.maven_pom_path }}/target/artifact.jar


